


const players = [
  // --- Premier League (200 Players) ---
  { id: 1, name: "Erling Haaland", nationality: "Norway", league: "Premier League", club: "Manchester City", position: "Attacker", age: 26, number: 9 },
  { id: 2, name: "Kevin De Bruyne", nationality: "Belgium", league: "Premier League", club: "Manchester City", position: "Midfielder", age: 35, number: 17 },
  { id: 3, name: "Phil Foden", nationality: "England", league: "Premier League", club: "Manchester City", position: "Attacker", age: 26, number: 47 },
  { id: 4, name: "Rodri", nationality: "Spain", league: "Premier League", club: "Manchester City", position: "Midfielder", age: 30, number: 16 },
  { id: 5, name: "Bernardo Silva", nationality: "Portugal", league: "Premier League", club: "Manchester City", position: "Midfielder", age: 31, number: 20 },
  { id: 6, name: "Rúben Dias", nationality: "Portugal", league: "Premier League", club: "Manchester City", position: "Defender", age: 29, number: 3 },
  { id: 7, name: "Ederson", nationality: "Brazil", league: "Premier League", club: "Manchester City", position: "Goalkeeper", age: 32, number: 31 },
  { id: 8, name: "Kyle Walker", nationality: "England", league: "Premier League", club: "Manchester City", position: "Defender", age: 36, number: 2 },
  { id: 9, name: "John Stones", nationality: "England", league: "Premier League", club: "Manchester City", position: "Defender", age: 32, number: 5 },
  { id: 10, name: "Jack Grealish", nationality: "England", league: "Premier League", club: "Manchester City", position: "Attacker", age: 30, number: 10 },
  { id: 11, name: "Manuel Akanji", nationality: "Switzerland", league: "Premier League", club: "Manchester City", position: "Defender", age: 31, number: 25 },
  { id: 12, name: "Nathan Aké", nationality: "Netherlands", league: "Premier League", club: "Manchester City", position: "Defender", age: 31, number: 6 },
  { id: 13, name: "Jérémy Doku", nationality: "Belgium", league: "Premier League", club: "Manchester City", position: "Attacker", age: 24, number: 11 },
  { id: 14, name: "Joško Gvardiol", nationality: "Croatia", league: "Premier League", club: "Manchester City", position: "Defender", age: 24, number: 24 },
  { id: 15, name: "Mateo Kovačić", nationality: "Croatia", league: "Premier League", club: "Manchester City", position: "Midfielder", age: 32, number: 8 },
  { id: 16, name: "Savinho", nationality: "Brazil", league: "Premier League", club: "Manchester City", position: "Attacker", age: 22, number: 26 },
  { id: 17, name: "Rico Lewis", nationality: "England", league: "Premier League", club: "Manchester City", position: "Defender", age: 21, number: 82 },
  { id: 18, name: "Stefan Ortega", nationality: "Germany", league: "Premier League", club: "Manchester City", position: "Goalkeeper", age: 33, number: 18 },
  { id: 19, name: "Bukayo Saka", nationality: "England", league: "Premier League", club: "Arsenal", position: "Attacker", age: 24, number: 7 },
  { id: 20, name: "Martin Ødegaard", nationality: "Norway", league: "Premier League", club: "Arsenal", position: "Midfielder", age: 27, number: 8 },
  { id: 21, name: "Declan Rice", nationality: "England", league: "Premier League", club: "Arsenal", position: "Midfielder", age: 27, number: 41 },
  { id: 22, name: "William Saliba", nationality: "France", league: "Premier League", club: "Arsenal", position: "Defender", age: 25, number: 2 },
  { id: 23, name: "Gabriel Magalhães", nationality: "Brazil", league: "Premier League", club: "Arsenal", position: "Defender", age: 28, number: 6 },
  { id: 24, name: "Ben White", nationality: "England", league: "Premier League", club: "Arsenal", position: "Defender", age: 28, number: 4 },
  { id: 25, name: "Kai Havertz", nationality: "Germany", league: "Premier League", club: "Arsenal", position: "Attacker", age: 27, number: 29 },
  { id: 26, name: "Gabriel Martinelli", nationality: "Brazil", league: "Premier League", club: "Arsenal", position: "Attacker", age: 25, number: 11 },
  { id: 27, name: "Leandro Trossard", nationality: "Belgium", league: "Premier League", club: "Arsenal", position: "Attacker", age: 31, number: 19 },
  { id: 28, name: "Thomas Partey", nationality: "Ghana", league: "Premier League", club: "Arsenal", position: "Midfielder", age: 33, number: 5 },
  { id: 29, name: "Jurriën Timber", nationality: "Netherlands", league: "Premier League", club: "Arsenal", position: "Defender", age: 25, number: 12 },
  { id: 30, name: "David Raya", nationality: "Spain", league: "Premier League", club: "Arsenal", position: "Goalkeeper", age: 30, number: 22 },
  { id: 31, name: "Takehiro Tomiyasu", nationality: "Japan", league: "Premier League", club: "Arsenal", position: "Defender", age: 27, number: 18 },
  { id: 32, name: "Oleksandr Zinchenko", nationality: "Ukraine", league: "Premier League", club: "Arsenal", position: "Defender", age: 29, number: 17 },
  { id: 33, name: "Gabriel Jesus", nationality: "Brazil", league: "Premier League", club: "Arsenal", position: "Attacker", age: 29, number: 9 },
  { id: 34, name: "Riccardo Calafiori", nationality: "Italy", league: "Premier League", club: "Arsenal", position: "Defender", age: 24, number: 33 },
  { id: 35, name: "Mikel Merino", nationality: "Spain", league: "Premier League", club: "Arsenal", position: "Midfielder", age: 30, number: 23 },
  { id: 36, name: "Jorginho", nationality: "Italy", league: "Premier League", club: "Arsenal", position: "Midfielder", age: 34, number: 20 },
  { id: 37, name: "Mohamed Salah", nationality: "Egypt", league: "Premier League", club: "Liverpool", position: "Attacker", age: 34, number: 11 },
  { id: 38, name: "Virgil van Dijk", nationality: "Netherlands", league: "Premier League", club: "Liverpool", position: "Defender", age: 35, number: 4 },
  { id: 39, name: "Trent Alexander-Arnold", nationality: "England", league: "Premier League", club: "Liverpool", position: "Defender", age: 27, number: 66 },
  { id: 40, name: "Alisson", nationality: "Brazil", league: "Premier League", club: "Liverpool", position: "Goalkeeper", age: 33, number: 1 },
  { id: 41, name: "Alexis Mac Allister", nationality: "Argentina", league: "Premier League", club: "Liverpool", position: "Midfielder", age: 27, number: 10 },
  { id: 42, name: "Dominik Szoboszlai", nationality: "Hungary", league: "Premier League", club: "Liverpool", position: "Midfielder", age: 25, number: 8 },
  { id: 43, name: "Luis Díaz", nationality: "Colombia", league: "Premier League", club: "Liverpool", position: "Attacker", age: 29, number: 7 },
  { id: 44, name: "Darwin Núñez", nationality: "Uruguay", league: "Premier League", club: "Liverpool", position: "Attacker", age: 27, number: 9 },
  { id: 45, name: "Diogo Jota", nationality: "Portugal", league: "Premier League", club: "Liverpool", position: "Attacker", age: 29, number: 20 },
  { id: 46, name: "Andrew Robertson", nationality: "Scotland", league: "Premier League", club: "Liverpool", position: "Defender", age: 32, number: 26 },
  { id: 47, name: "Cody Gakpo", nationality: "Netherlands", league: "Premier League", club: "Liverpool", position: "Attacker", age: 27, number: 18 },
  { id: 48, name: "Harvey Elliott", nationality: "England", league: "Premier League", club: "Liverpool", position: "Midfielder", age: 23, number: 19 },
  { id: 49, name: "Ibrahima Konaté", nationality: "France", league: "Premier League", club: "Liverpool", position: "Defender", age: 27, number: 5 },
  { id: 50, name: "Ryan Gravenberch", nationality: "Netherlands", league: "Premier League", club: "Liverpool", position: "Midfielder", age: 24, number: 38 },
  { id: 51, name: "Curtis Jones", nationality: "England", league: "Premier League", club: "Liverpool", position: "Midfielder", age: 25, number: 17 },
  { id: 52, name: "Federico Chiesa", nationality: "Italy", league: "Premier League", club: "Liverpool", position: "Attacker", age: 28, number: 14 },
  { id: 53, name: "Wataru Endo", nationality: "Japan", league: "Premier League", club: "Liverpool", position: "Midfielder", age: 33, number: 3 },
  { id: 54, name: "Joe Gomez", nationality: "England", league: "Premier League", club: "Liverpool", position: "Defender", age: 29, number: 2 },
  { id: 55, name: "Cole Palmer", nationality: "England", league: "Premier League", club: "Chelsea", position: "Attacker", age: 24, number: 20 },
  { id: 56, name: "Enzo Fernández", nationality: "Argentina", league: "Premier League", club: "Chelsea", position: "Midfielder", age: 25, number: 8 },
  { id: 57, name: "Moisés Caicedo", nationality: "Ecuador", league: "Premier League", club: "Chelsea", position: "Midfielder", age: 24, number: 25 },
  { id: 58, name: "Reece James", nationality: "England", league: "Premier League", club: "Chelsea", position: "Defender", age: 26, number: 24 },
  { id: 59, name: "Marc Cucurella", nationality: "Spain", league: "Premier League", club: "Chelsea", position: "Defender", age: 28, number: 3 },
  { id: 60, name: "Nicolas Jackson", nationality: "Senegal", league: "Premier League", club: "Chelsea", position: "Attacker", age: 25, number: 15 },
  { id: 61, name: "Christopher Nkunku", nationality: "France", league: "Premier League", club: "Chelsea", position: "Attacker", age: 28, number: 18 },
  { id: 62, name: "Levi Colwill", nationality: "England", league: "Premier League", club: "Chelsea", position: "Defender", age: 23, number: 6 },
  { id: 63, name: "Malo Gusto", nationality: "France", league: "Premier League", club: "Chelsea", position: "Defender", age: 23, number: 27 },
  { id: 64, name: "Mykhailo Mudryk", nationality: "Ukraine", league: "Premier League", club: "Chelsea", position: "Attacker", age: 25, number: 10 },
  { id: 65, name: "Robert Sánchez", nationality: "Spain", league: "Premier League", club: "Chelsea", position: "Goalkeeper", age: 28, number: 1 },
  { id: 66, name: "Noni Madueke", nationality: "England", league: "Premier League", club: "Chelsea", position: "Attacker", age: 24, number: 11 },
  { id: 67, name: "Pedro Neto", nationality: "Portugal", league: "Premier League", club: "Chelsea", position: "Attacker", age: 26, number: 7 },
  { id: 68, name: "Jadon Sancho", nationality: "England", league: "Premier League", club: "Chelsea", position: "Attacker", age: 26, number: 19 },
  { id: 69, name: "Wesley Fofana", nationality: "France", league: "Premier League", club: "Chelsea", position: "Defender", age: 25, number: 29 },
  { id: 70, name: "João Félix", nationality: "Portugal", league: "Premier League", club: "Chelsea", position: "Attacker", age: 26, number: 14 },
  { id: 71, name: "Romeo Lavia", nationality: "Belgium", league: "Premier League", club: "Chelsea", position: "Midfielder", age: 22, number: 45 },
  { id: 72, name: "Filip Jørgensen", nationality: "Denmark", league: "Premier League", club: "Chelsea", position: "Goalkeeper", age: 24, number: 12 },
  { id: 73, name: "Bruno Fernandes", nationality: "Portugal", league: "Premier League", club: "Manchester United", position: "Midfielder", age: 31, number: 8 },
  { id: 74, name: "Marcus Rashford", nationality: "England", league: "Premier League", club: "Manchester United", position: "Attacker", age: 28, number: 10 },
  { id: 75, name: "Alejandro Garnacho", nationality: "Argentina", league: "Premier League", club: "Manchester United", position: "Attacker", age: 22, number: 17 },
  { id: 76, name: "Kobbie Mainoo", nationality: "England", league: "Premier League", club: "Manchester United", position: "Midfielder", age: 21, number: 37 },
  { id: 77, name: "Lisandro Martínez", nationality: "Argentina", league: "Premier League", club: "Manchester United", position: "Defender", age: 28, number: 6 },
  { id: 78, name: "André Onana", nationality: "Cameroon", league: "Premier League", club: "Manchester United", position: "Goalkeeper", age: 30, number: 24 },
  { id: 79, name: "Luke Shaw", nationality: "England", league: "Premier League", club: "Manchester United", position: "Defender", age: 31, number: 23 },
  { id: 80, name: "Diogo Dalot", nationality: "Portugal", league: "Premier League", club: "Manchester United", position: "Defender", age: 27, number: 20 },
  { id: 81, name: "Casemiro", nationality: "Brazil", league: "Premier League", club: "Manchester United", position: "Midfielder", age: 34, number: 18 },
  { id: 82, name: "Rasmus Højlund", nationality: "Denmark", league: "Premier League", club: "Manchester United", position: "Attacker", age: 23, number: 9 },
  { id: 83, name: "Mason Mount", nationality: "England", league: "Premier League", club: "Manchester United", position: "Midfielder", age: 27, number: 7 },
  { id: 84, name: "Matthijs de Ligt", nationality: "Netherlands", league: "Premier League", club: "Manchester United", position: "Defender", age: 26, number: 4 },
  { id: 85, name: "Leny Yoro", nationality: "France", league: "Premier League", club: "Manchester United", position: "Defender", age: 20, number: 15 },
  { id: 86, name: "Joshua Zirkzee", nationality: "Netherlands", league: "Premier League", club: "Manchester United", position: "Attacker", age: 25, number: 11 },
  { id: 87, name: "Manuel Ugarte", nationality: "Uruguay", league: "Premier League", club: "Manchester United", position: "Midfielder", age: 25, number: 25 },
  { id: 88, name: "Noussair Mazraoui", nationality: "Morocco", league: "Premier League", club: "Manchester United", position: "Defender", age: 28, number: 3 },
  { id: 89, name: "Harry Maguire", nationality: "England", league: "Premier League", club: "Manchester United", position: "Defender", age: 33, number: 5 },
  { id: 90, name: "Amad Diallo", nationality: "Ivory Coast", league: "Premier League", club: "Manchester United", position: "Attacker", age: 24, number: 16 },
  { id: 91, name: "Alexander Isak", nationality: "Sweden", league: "Premier League", club: "Newcastle United", position: "Attacker", age: 26, number: 14 },
  { id: 92, name: "Bruno Guimarães", nationality: "Brazil", league: "Premier League", club: "Newcastle United", position: "Midfielder", age: 28, number: 39 },
  { id: 93, name: "Anthony Gordon", nationality: "England", league: "Premier League", club: "Newcastle United", position: "Attacker", age: 25, number: 10 },
  { id: 94, name: "Kieran Trippier", nationality: "England", league: "Premier League", club: "Newcastle United", position: "Defender", age: 35, number: 2 },
  { id: 95, name: "Sven Botman", nationality: "Netherlands", league: "Premier League", club: "Newcastle United", position: "Defender", age: 26, number: 4 },
  { id: 96, name: "Nick Pope", nationality: "England", league: "Premier League", club: "Newcastle United", position: "Goalkeeper", age: 34, number: 22 },
  { id: 97, name: "Joelinton", nationality: "Brazil", league: "Premier League", club: "Newcastle United", position: "Midfielder", age: 29, number: 7 },
  { id: 98, name: "Fabian Schär", nationality: "Switzerland", league: "Premier League", club: "Newcastle United", position: "Defender", age: 34, number: 5 },
  { id: 99, name: "Dan Burn", nationality: "England", league: "Premier League", club: "Newcastle United", position: "Defender", age: 34, number: 33 },
  { id: 100, name: "Callum Wilson", nationality: "England", league: "Premier League", club: "Newcastle United", position: "Attacker", age: 34, number: 9 },
  { id: 101, name: "Harvey Barnes", nationality: "England", league: "Premier League", club: "Newcastle United", position: "Attacker", age: 28, number: 11 },
  { id: 102, name: "Sean Longstaff", nationality: "England", league: "Premier League", club: "Newcastle United", position: "Midfielder", age: 28, number: 36 },
  { id: 103, name: "Sandro Tonali", nationality: "Italy", league: "Premier League", club: "Newcastle United", position: "Midfielder", age: 26, number: 8 },
  { id: 104, name: "Tino Livramento", nationality: "England", league: "Premier League", club: "Newcastle United", position: "Defender", age: 23, number: 21 },
  { id: 105, name: "Lewis Hall", nationality: "England", league: "Premier League", club: "Newcastle United", position: "Defender", age: 21, number: 20 },
  { id: 106, name: "Jacob Murphy", nationality: "England", league: "Premier League", club: "Newcastle United", position: "Attacker", age: 31, number: 23 },
  { id: 107, name: "Son Heung-min", nationality: "South Korea", league: "Premier League", club: "Tottenham Hotspur", position: "Attacker", age: 34, number: 7 },
  { id: 108, name: "James Maddison", nationality: "England", league: "Premier League", club: "Tottenham Hotspur", position: "Midfielder", age: 29, number: 10 },
  { id: 109, name: "Cristian Romero", nationality: "Argentina", league: "Premier League", club: "Tottenham Hotspur", position: "Defender", age: 28, number: 17 },
  { id: 110, name: "Micky van de Ven", nationality: "Netherlands", league: "Premier League", club: "Tottenham Hotspur", position: "Defender", age: 25, number: 37 },
  { id: 111, name: "Pedro Porro", nationality: "Spain", league: "Premier League", club: "Tottenham Hotspur", position: "Defender", age: 26, number: 23 },
  { id: 112, name: "Guglielmo Vicario", nationality: "Italy", league: "Premier League", club: "Tottenham Hotspur", position: "Goalkeeper", age: 29, number: 1 },
  { id: 113, name: "Dejan Kulusevski", nationality: "Sweden", league: "Premier League", club: "Tottenham Hotspur", position: "Midfielder", age: 26, number: 21 },
  { id: 114, name: "Richarlison", nationality: "Brazil", league: "Premier League", club: "Tottenham Hotspur", position: "Attacker", age: 29, number: 9 },
  { id: 115, name: "Pape Matar Sarr", nationality: "Senegal", league: "Premier League", club: "Tottenham Hotspur", position: "Midfielder", age: 23, number: 29 },
  { id: 116, name: "Yves Bissouma", nationality: "Mali", league: "Premier League", club: "Tottenham Hotspur", position: "Midfielder", age: 29, number: 8 },
  { id: 117, name: "Brennan Johnson", nationality: "Wales", league: "Premier League", club: "Tottenham Hotspur", position: "Attacker", age: 25, number: 22 },
  { id: 118, name: "Destiny Udogie", nationality: "Italy", league: "Premier League", club: "Tottenham Hotspur", position: "Defender", age: 23, number: 38 },
  { id: 119, name: "Rodrigo Bentancur", nationality: "Uruguay", league: "Premier League", club: "Tottenham Hotspur", position: "Midfielder", age: 29, number: 30 },
  { id: 120, name: "Radu Drăgușin", nationality: "Romania", league: "Premier League", club: "Tottenham Hotspur", position: "Defender", age: 24, number: 6 },
  { id: 121, name: "Dominic Solanke", nationality: "England", league: "Premier League", club: "Tottenham Hotspur", position: "Attacker", age: 28, number: 19 },
  { id: 122, name: "Archie Gray", nationality: "England", league: "Premier League", club: "Tottenham Hotspur", position: "Midfielder", age: 20, number: 14 },
  { id: 123, name: "Lucas Bergvall", nationality: "Sweden", league: "Premier League", club: "Tottenham Hotspur", position: "Midfielder", age: 20, number: 15 },
  { id: 124, name: "Wilson Odobert", nationality: "France", league: "Premier League", club: "Tottenham Hotspur", position: "Attacker", age: 21, number: 28 },
  { id: 125, name: "Ollie Watkins", nationality: "England", league: "Premier League", club: "Aston Villa", position: "Attacker", age: 30, number: 11 },
  { id: 126, name: "Emiliano Martínez", nationality: "Argentina", league: "Premier League", club: "Aston Villa", position: "Goalkeeper", age: 33, number: 23 },
  { id: 127, name: "John McGinn", nationality: "Scotland", league: "Premier League", club: "Aston Villa", position: "Midfielder", age: 31, number: 7 },
  { id: 128, name: "Leon Bailey", nationality: "Jamaica", league: "Premier League", club: "Aston Villa", position: "Attacker", age: 28, number: 31 },
  { id: 129, name: "Youri Tielemans", nationality: "Belgium", league: "Premier League", club: "Aston Villa", position: "Midfielder", age: 29, number: 8 },
  { id: 130, name: "Pau Torres", nationality: "Spain", league: "Premier League", club: "Aston Villa", position: "Defender", age: 29, number: 14 },
  { id: 131, name: "Ezri Konsa", nationality: "England", league: "Premier League", club: "Aston Villa", position: "Defender", age: 28, number: 4 },
  { id: 132, name: "Matty Cash", nationality: "Poland", league: "Premier League", club: "Aston Villa", position: "Defender", age: 28, number: 2 },
  { id: 133, name: "Jacob Ramsey", nationality: "England", league: "Premier League", club: "Aston Villa", position: "Midfielder", age: 25, number: 41 },
  { id: 134, name: "Jhon Durán", nationality: "Colombia", league: "Premier League", club: "Aston Villa", position: "Attacker", age: 22, number: 9 },
  { id: 135, name: "Boubacar Kamara", nationality: "France", league: "Premier League", club: "Aston Villa", position: "Midfielder", age: 26, number: 44 },
  { id: 136, name: "Amadou Onana", nationality: "Belgium", league: "Premier League", club: "Aston Villa", position: "Midfielder", age: 24, number: 24 },
  { id: 137, name: "Ian Maatsen", nationality: "Netherlands", league: "Premier League", club: "Aston Villa", position: "Defender", age: 24, number: 22 },
  { id: 138, name: "Morgan Rogers", nationality: "England", league: "Premier League", club: "Aston Villa", position: "Attacker", age: 24, number: 27 },
  { id: 139, name: "Lucas Digne", nationality: "France", league: "Premier League", club: "Aston Villa", position: "Defender", age: 33, number: 12 },
  { id: 140, name: "Diego Carlos", nationality: "Brazil", league: "Premier League", club: "Aston Villa", position: "Defender", age: 33, number: 3 },
  { id: 141, name: "Jarrod Bowen", nationality: "England", league: "Premier League", club: "West Ham United", position: "Attacker", age: 29, number: 20 },
  { id: 142, name: "Mohammed Kudus", nationality: "Ghana", league: "Premier League", club: "West Ham United", position: "Attacker", age: 26, number: 14 },
  { id: 143, name: "Lucas Paquetá", nationality: "Brazil", league: "Premier League", club: "West Ham United", position: "Midfielder", age: 28, number: 10 },
  { id: 144, name: "Edson Álvarez", nationality: "Mexico", league: "Premier League", club: "West Ham United", position: "Midfielder", age: 28, number: 19 },
  { id: 145, name: "Emerson Palmieri", nationality: "Italy", league: "Premier League", club: "West Ham United", position: "Defender", age: 32, number: 33 },
  { id: 146, name: "Alphonse Areola", nationality: "France", league: "Premier League", club: "West Ham United", position: "Goalkeeper", age: 33, number: 23 },
  { id: 147, name: "Tomáš Souček", nationality: "Czech Republic", league: "Premier League", club: "West Ham United", position: "Midfielder", age: 31, number: 28 },
  { id: 148, name: "Niclas Füllkrug", nationality: "Germany", league: "Premier League", club: "West Ham United", position: "Attacker", age: 33, number: 11 },
  { id: 149, name: "Crysencio Summerville", nationality: "Netherlands", league: "Premier League", club: "West Ham United", position: "Attacker", age: 24, number: 7 },
  { id: 150, name: "Aaron Wan-Bissaka", nationality: "England", league: "Premier League", club: "West Ham United", position: "Defender", age: 28, number: 29 },
  { id: 151, name: "Max Kilman", nationality: "England", league: "Premier League", club: "West Ham United", position: "Defender", age: 29, number: 26 },
  { id: 152, name: "Guido Rodríguez", nationality: "Argentina", league: "Premier League", club: "West Ham United", position: "Midfielder", age: 32, number: 24 },
  { id: 153, name: "Kaoru Mitoma", nationality: "Japan", league: "Premier League", club: "Brighton & Hove Albion", position: "Attacker", age: 29, number: 22 },
  { id: 154, name: "Simon Adingra", nationality: "Ivory Coast", league: "Premier League", club: "Brighton & Hove Albion", position: "Attacker", age: 24, number: 11 },
  { id: 155, name: "João Pedro", nationality: "Brazil", league: "Premier League", club: "Brighton & Hove Albion", position: "Attacker", age: 24, number: 9 },
  { id: 156, name: "Evan Ferguson", nationality: "Ireland", league: "Premier League", club: "Brighton & Hove Albion", position: "Attacker", age: 21, number: 28 },
  { id: 157, name: "Lewis Dunk", nationality: "England", league: "Premier League", club: "Brighton & Hove Albion", position: "Defender", age: 34, number: 5 },
  { id: 158, name: "Pervis Estupiñán", nationality: "Ecuador", league: "Premier League", club: "Brighton & Hove Albion", position: "Defender", age: 28, number: 30 },
  { id: 159, name: "Bart Verbruggen", nationality: "Netherlands", league: "Premier League", club: "Brighton & Hove Albion", position: "Goalkeeper", age: 23, number: 1 },
  { id: 160, name: "Julio Enciso", nationality: "Paraguay", league: "Premier League", club: "Brighton & Hove Albion", position: "Attacker", age: 22, number: 10 },
  { id: 161, name: "Georginio Rutter", nationality: "France", league: "Premier League", club: "Brighton & Hove Albion", position: "Attacker", age: 24, number: 14 },
  { id: 162, name: "Yankuba Minteh", nationality: "Gambia", league: "Premier League", club: "Brighton & Hove Albion", position: "Attacker", age: 22, number: 17 },
  { id: 163, name: "Mats Wieffer", nationality: "Netherlands", league: "Premier League", club: "Brighton & Hove Albion", position: "Midfielder", age: 26, number: 27 },
  { id: 164, name: "Carlos Baleba", nationality: "Cameroon", league: "Premier League", club: "Brighton & Hove Albion", position: "Midfielder", age: 22, number: 20 },
  { id: 165, name: "Eberechi Eze", nationality: "England", league: "Premier League", club: "Crystal Palace", position: "Midfielder", age: 28, number: 10 },
  { id: 166, name: "Marc Guéhi", nationality: "England", league: "Premier League", club: "Crystal Palace", position: "Defender", age: 26, number: 6 },
  { id: 167, name: "Jean-Philippe Mateta", nationality: "France", league: "Premier League", club: "Crystal Palace", position: "Attacker", age: 29, number: 14 },
  { id: 168, name: "Tyrick Mitchell", nationality: "England", league: "Premier League", club: "Crystal Palace", position: "Defender", age: 26, number: 3 },
  { id: 169, name: "Adam Wharton", nationality: "England", league: "Premier League", club: "Crystal Palace", position: "Midfielder", age: 22, number: 20 },
  { id: 170, name: "Dean Henderson", nationality: "England", league: "Premier League", club: "Crystal Palace", position: "Goalkeeper", age: 29, number: 1 },
  { id: 171, name: "Daniel Muñoz", nationality: "Colombia", league: "Premier League", club: "Crystal Palace", position: "Defender", age: 30, number: 12 },
  { id: 172, name: "Daichi Kamada", nationality: "Japan", league: "Premier League", club: "Crystal Palace", position: "Midfielder", age: 30, number: 18 },
  { id: 173, name: "Antoine Semenyo", nationality: "Ghana", league: "Premier League", club: "AFC Bournemouth", position: "Attacker", age: 26, number: 24 },
  { id: 174, name: "Marcus Tavernier", nationality: "England", league: "Premier League", club: "AFC Bournemouth", position: "Midfielder", age: 27, number: 16 },
  { id: 175, name: "Illia Zabarnyi", nationality: "Ukraine", league: "Premier League", club: "AFC Bournemouth", position: "Defender", age: 23, number: 27 },
  { id: 176, name: "Milos Kerkez", nationality: "Hungary", league: "Premier League", club: "AFC Bournemouth", position: "Defender", age: 22, number: 3 },
  { id: 177, name: "Ryan Christie", nationality: "Scotland", league: "Premier League", club: "AFC Bournemouth", position: "Midfielder", age: 31, number: 10 },
  { id: 178, name: "Justin Kluivert", nationality: "Netherlands", league: "Premier League", club: "AFC Bournemouth", position: "Attacker", age: 27, number: 19 },
  { id: 179, name: "Evanilson", nationality: "Brazil", league: "Premier League", club: "AFC Bournemouth", position: "Attacker", age: 26, number: 9 },
  { id: 180, name: "Kepa Arrizabalaga", nationality: "Spain", league: "Premier League", club: "AFC Bournemouth", position: "Goalkeeper", age: 31, number: 13 },
  { id: 181, name: "Bryan Mbeumo", nationality: "Cameroon", league: "Premier League", club: "Brentford", position: "Attacker", age: 27, number: 19 },
  { id: 182, name: "Yoane Wissa", nationality: "DR Congo", league: "Premier League", club: "Brentford", position: "Attacker", age: 29, number: 11 },
  { id: 183, name: "Christian Nørgaard", nationality: "Denmark", league: "Premier League", club: "Brentford", position: "Midfielder", age: 32, number: 6 },
  { id: 184, name: "Mathias Jensen", nationality: "Denmark", league: "Premier League", club: "Brentford", position: "Midfielder", age: 30, number: 8 },
  { id: 185, name: "Mark Flekken", nationality: "Netherlands", league: "Premier League", club: "Brentford", position: "Goalkeeper", age: 33, number: 1 },
  { id: 186, name: "Igor Thiago", nationality: "Brazil", league: "Premier League", club: "Brentford", position: "Attacker", age: 25, number: 9 },
  { id: 187, name: "Sepp van den Berg", nationality: "Netherlands", league: "Premier League", club: "Brentford", position: "Defender", age: 24, number: 4 },
  { id: 188, name: "Mikkel Damsgaard", nationality: "Denmark", league: "Premier League", club: "Brentford", position: "Midfielder", age: 26, number: 24 },
  { id: 189, name: "Antonee Robinson", nationality: "USA", league: "Premier League", club: "Fulham", position: "Defender", age: 28, number: 33 },
  { id: 190, name: "Andreas Pereira", nationality: "Brazil", league: "Premier League", club: "Fulham", position: "Midfielder", age: 30, number: 18 },
  { id: 191, name: "Alex Iwobi", nationality: "Nigeria", league: "Premier League", club: "Fulham", position: "Midfielder", age: 30, number: 17 },
  { id: 192, name: "Rodrigo Muniz", nationality: "Brazil", league: "Premier League", club: "Fulham", position: "Attacker", age: 25, number: 9 },
  { id: 193, name: "Bernd Leno", nationality: "Germany", league: "Premier League", club: "Fulham", position: "Goalkeeper", age: 34, number: 1 },
  { id: 194, name: "Emile Smith Rowe", nationality: "England", league: "Premier League", club: "Fulham", position: "Midfielder", age: 26, number: 32 },
  { id: 195, name: "Joachim Andersen", nationality: "Denmark", league: "Premier League", club: "Fulham", position: "Defender", age: 30, number: 5 },
  { id: 196, name: "Sander Berge", nationality: "Norway", league: "Premier League", club: "Fulham", position: "Midfielder", age: 28, number: 16 },
  { id: 197, name: "Jordan Pickford", nationality: "England", league: "Premier League", club: "Everton", position: "Goalkeeper", age: 32, number: 1 },
  { id: 198, name: "Jarrad Branthwaite", nationality: "England", league: "Premier League", club: "Everton", position: "Defender", age: 24, number: 32 },
  { id: 199, name: "James Tarkowski", nationality: "England", league: "Premier League", club: "Everton", position: "Defender", age: 33, number: 6 },
  { id: 200, name: "Dwight McNeil", nationality: "England", league: "Premier League", club: "Everton", position: "Midfielder", age: 26, number: 7 },

  // --- La Liga (80 Players) ---
  { id: 201, name: "Vinícius Júnior", nationality: "Brazil", league: "La Liga", club: "Real Madrid", position: "Attacker", age: 26, number: 7 },
  { id: 202, name: "Jude Bellingham", nationality: "England", league: "La Liga", club: "Real Madrid", position: "Midfielder", age: 23, number: 5 },
  { id: 203, name: "Kylian Mbappé", nationality: "France", league: "La Liga", club: "Real Madrid", position: "Attacker", age: 27, number: 9 },
  { id: 204, name: "Rodrygo", nationality: "Brazil", league: "La Liga", club: "Real Madrid", position: "Attacker", age: 25, number: 11 },
  { id: 205, name: "Federico Valverde", nationality: "Uruguay", league: "La Liga", club: "Real Madrid", position: "Midfielder", age: 28, number: 8 },
  { id: 206, name: "Eduardo Camavinga", nationality: "France", league: "La Liga", club: "Real Madrid", position: "Midfielder", age: 23, number: 6 },
  { id: 207, name: "Aurélien Tchouaméni", nationality: "France", league: "La Liga", club: "Real Madrid", position: "Midfielder", age: 26, number: 14 },
  { id: 208, name: "Antonio Rüdiger", nationality: "Germany", league: "La Liga", club: "Real Madrid", position: "Defender", age: 33, number: 22 },
  { id: 209, name: "Thibaut Courtois", nationality: "Belgium", league: "La Liga", club: "Real Madrid", position: "Goalkeeper", age: 34, number: 1 },
  { id: 210, name: "Éder Militão", nationality: "Brazil", league: "La Liga", club: "Real Madrid", position: "Defender", age: 28, number: 3 },
  { id: 211, name: "Dani Carvajal", nationality: "Spain", league: "La Liga", club: "Real Madrid", position: "Defender", age: 34, number: 2 },
  { id: 212, name: "Ferland Mendy", nationality: "France", league: "La Liga", club: "Real Madrid", position: "Defender", age: 31, number: 23 },
  { id: 213, name: "Brahim Díaz", nationality: "Morocco", league: "La Liga", club: "Real Madrid", position: "Midfielder", age: 27, number: 21 },
  { id: 214, name: "Arda Güler", nationality: "Turkey", league: "La Liga", club: "Real Madrid", position: "Midfielder", age: 21, number: 15 },
  { id: 215, name: "Endrick", nationality: "Brazil", league: "La Liga", club: "Real Madrid", position: "Attacker", age: 20, number: 16 },
  { id: 216, name: "Luka Modrić", nationality: "Croatia", league: "La Liga", club: "Real Madrid", position: "Midfielder", age: 40, number: 10 },
  { id: 217, name: "Lucas Vázquez", nationality: "Spain", league: "La Liga", club: "Real Madrid", position: "Defender", age: 35, number: 17 },
  { id: 218, name: "Andriy Lunin", nationality: "Ukraine", league: "La Liga", club: "Real Madrid", position: "Goalkeeper", age: 27, number: 13 },
  { id: 219, name: "Lamine Yamal", nationality: "Spain", league: "La Liga", club: "FC Barcelona", position: "Attacker", age: 19, number: 19 },
  { id: 220, name: "Robert Lewandowski", nationality: "Poland", league: "La Liga", club: "FC Barcelona", position: "Attacker", age: 37, number: 9 },
  { id: 221, name: "Pedri", nationality: "Spain", league: "La Liga", club: "FC Barcelona", position: "Midfielder", age: 23, number: 8 },
  { id: 222, name: "Gavi", nationality: "Spain", league: "La Liga", club: "FC Barcelona", position: "Midfielder", age: 21, number: 6 },
  { id: 223, name: "Frenkie de Jong", nationality: "Netherlands", league: "La Liga", club: "FC Barcelona", position: "Midfielder", age: 29, number: 21 },
  { id: 224, name: "Raphinha", nationality: "Brazil", league: "La Liga", club: "FC Barcelona", position: "Attacker", age: 29, number: 11 },
  { id: 225, name: "Ronald Araújo", nationality: "Uruguay", league: "La Liga", club: "FC Barcelona", position: "Defender", age: 27, number: 4 },
  { id: 226, name: "Jules Koundé", nationality: "France", league: "La Liga", club: "FC Barcelona", position: "Defender", age: 27, number: 23 },
  { id: 227, name: "Marc-André ter Stegen", nationality: "Germany", league: "La Liga", club: "FC Barcelona", position: "Goalkeeper", age: 34, number: 1 },
  { id: 228, name: "Alejandro Balde", nationality: "Spain", league: "La Liga", club: "FC Barcelona", position: "Defender", age: 22, number: 3 },
  { id: 229, name: "Pau Cubarsí", nationality: "Spain", league: "La Liga", club: "FC Barcelona", position: "Defender", age: 19, number: 2 },
  { id: 230, name: "Dani Olmo", nationality: "Spain", league: "La Liga", club: "FC Barcelona", position: "Midfielder", age: 28, number: 20 },
  { id: 231, name: "Fermín López", nationality: "Spain", league: "La Liga", club: "FC Barcelona", position: "Midfielder", age: 23, number: 16 },
  { id: 232, name: "Ferran Torres", nationality: "Spain", league: "La Liga", club: "FC Barcelona", position: "Attacker", age: 26, number: 7 },
  { id: 233, name: "Andreas Christensen", nationality: "Denmark", league: "La Liga", club: "FC Barcelona", position: "Defender", age: 30, number: 15 },
  { id: 234, name: "Marc Casadó", nationality: "Spain", league: "La Liga", club: "FC Barcelona", position: "Midfielder", age: 22, number: 17 },
  { id: 235, name: "Iñigo Martínez", nationality: "Spain", league: "La Liga", club: "FC Barcelona", position: "Defender", age: 35, number: 5 },
  { id: 236, name: "Antoine Griezmann", nationality: "France", league: "La Liga", club: "Atlético Madrid", position: "Attacker", age: 35, number: 7 },
  { id: 237, name: "Julián Alvarez", nationality: "Argentina", league: "La Liga", club: "Atlético Madrid", position: "Attacker", age: 26, number: 19 },
  { id: 238, name: "Jan Oblak", nationality: "Slovenia", league: "La Liga", club: "Atlético Madrid", position: "Goalkeeper", age: 33, number: 13 },
  { id: 239, name: "Koke", nationality: "Spain", league: "La Liga", club: "Atlético Madrid", position: "Midfielder", age: 34, number: 6 },
  { id: 240, name: "Rodrigo De Paul", nationality: "Argentina", league: "La Liga", club: "Atlético Madrid", position: "Midfielder", age: 32, number: 5 },
  { id: 241, name: "Marcos Llorente", nationality: "Spain", league: "La Liga", club: "Atlético Madrid", position: "Midfielder", age: 31, number: 14 },
  { id: 242, name: "José María Giménez", nationality: "Uruguay", league: "La Liga", club: "Atlético Madrid", position: "Defender", age: 31, number: 2 },
  { id: 243, name: "Robin Le Normand", nationality: "Spain", league: "La Liga", club: "Atlético Madrid", position: "Defender", age: 29, number: 24 },
  { id: 244, name: "Conor Gallagher", nationality: "England", league: "La Liga", club: "Atlético Madrid", position: "Midfielder", age: 26, number: 4 },
  { id: 245, name: "Alexander Sørloth", nationality: "Norway", league: "La Liga", club: "Atlético Madrid", position: "Attacker", age: 30, number: 9 },
  { id: 246, name: "Samuel Lino", nationality: "Brazil", league: "La Liga", club: "Atlético Madrid", position: "Attacker", age: 26, number: 12 },
  { id: 247, name: "Pablo Barrios", nationality: "Spain", league: "La Liga", club: "Atlético Madrid", position: "Midfielder", age: 23, number: 8 },
  { id: 248, name: "Reinildo Mandava", nationality: "Mozambique", league: "La Liga", club: "Atlético Madrid", position: "Defender", age: 32, number: 23 },
  { id: 249, name: "Nico Williams", nationality: "Spain", league: "La Liga", club: "Athletic Club", position: "Attacker", age: 24, number: 10 },
  { id: 250, name: "Iñaki Williams", nationality: "Ghana", league: "La Liga", club: "Athletic Club", position: "Attacker", age: 32, number: 9 },
  { id: 251, name: "Oihan Sancet", nationality: "Spain", league: "La Liga", club: "Athletic Club", position: "Midfielder", age: 26, number: 8 },
  { id: 252, name: "Unai Simón", nationality: "Spain", league: "La Liga", club: "Athletic Club", position: "Goalkeeper", age: 29, number: 1 },
  { id: 253, name: "Dani Vivian", nationality: "Spain", league: "La Liga", club: "Athletic Club", position: "Defender", age: 27, number: 3 },
  { id: 254, name: "Aitor Paredes", nationality: "Spain", league: "La Liga", club: "Athletic Club", position: "Defender", age: 26, number: 4 },
  { id: 255, name: "Gorka Guruzeta", nationality: "Spain", league: "La Liga", club: "Athletic Club", position: "Attacker", age: 29, number: 12 },
  { id: 256, name: "Beñat Prados", nationality: "Spain", league: "La Liga", club: "Athletic Club", position: "Midfielder", age: 25, number: 24 },
  { id: 257, name: "Takefusa Kubo", nationality: "Japan", league: "La Liga", club: "Real Sociedad", position: "Attacker", age: 25, number: 14 },
  { id: 258, name: "Mikel Oyarzabal", nationality: "Spain", league: "La Liga", club: "Real Sociedad", position: "Attacker", age: 29, number: 10 },
  { id: 259, name: "Martín Zubimendi", nationality: "Spain", league: "La Liga", club: "Real Sociedad", position: "Midfielder", age: 27, number: 4 },
  { id: 260, name: "Álex Remiro", nationality: "Spain", league: "La Liga", club: "Real Sociedad", position: "Goalkeeper", age: 31, number: 1 },
  { id: 261, name: "Brais Méndez", nationality: "Spain", league: "La Liga", club: "Real Sociedad", position: "Midfielder", age: 29, number: 23 },
  { id: 262, name: "Igor Zubeldia", nationality: "Spain", league: "La Liga", club: "Real Sociedad", position: "Defender", age: 29, number: 5 },
  { id: 263, name: "Nayef Aguerd", nationality: "Morocco", league: "La Liga", club: "Real Sociedad", position: "Defender", age: 30, number: 21 },
  { id: 264, name: "Luka Sučić", nationality: "Croatia", league: "La Liga", club: "Real Sociedad", position: "Midfielder", age: 23, number: 24 },
  { id: 265, name: "Gerard Moreno", nationality: "Spain", league: "La Liga", club: "Villarreal CF", position: "Attacker", age: 34, number: 7 },
  { id: 266, name: "Álex Baena", nationality: "Spain", league: "La Liga", club: "Villarreal CF", position: "Midfielder", age: 25, number: 16 },
  { id: 267, name: "Yeremy Pino", nationality: "Spain", league: "La Liga", club: "Villarreal CF", position: "Attacker", age: 23, number: 21 },
  { id: 268, name: "Ayoze Pérez", nationality: "Spain", league: "La Liga", club: "Villarreal CF", position: "Attacker", age: 33, number: 22 },
  { id: 269, name: "Dani Parejo", nationality: "Spain", league: "La Liga", club: "Villarreal CF", position: "Midfielder", age: 37, number: 10 },
  { id: 270, name: "Nicolas Pépé", nationality: "Ivory Coast", league: "La Liga", club: "Villarreal CF", position: "Attacker", age: 31, number: 19 },
  { id: 271, name: "Isco", nationality: "Spain", league: "La Liga", club: "Real Betis", position: "Midfielder", age: 34, number: 22 },
  { id: 272, name: "Giovani Lo Celso", nationality: "Argentina", league: "La Liga", club: "Real Betis", position: "Midfielder", age: 30, number: 21 },
  { id: 273, name: "Vitor Roque", nationality: "Brazil", league: "La Liga", club: "Real Betis", position: "Attacker", age: 21, number: 8 },
  { id: 274, name: "Marc Roca", nationality: "Spain", league: "La Liga", club: "Real Betis", position: "Midfielder", age: 29, number: 21 },
  { id: 275, name: "Pablo Fornals", nationality: "Spain", league: "La Liga", club: "Real Betis", position: "Midfielder", age: 28, number: 18 },
  { id: 276, name: "Rui Silva", nationality: "Portugal", league: "La Liga", club: "Real Betis", position: "Goalkeeper", age: 32, number: 1 },
  { id: 277, name: "Jesús Navas", nationality: "Spain", league: "La Liga", club: "Sevilla FC", position: "Defender", age: 40, number: 16 },
  { id: 278, name: "Lucas Ocampos", nationality: "Argentina", league: "La Liga", club: "Sevilla FC", position: "Attacker", age: 32, number: 5 },
  { id: 279, name: "Loïc Badé", nationality: "France", league: "La Liga", club: "Sevilla FC", position: "Defender", age: 26, number: 22 },
  { id: 280, name: "Saúl Ñíguez", nationality: "Spain", league: "La Liga", club: "Sevilla FC", position: "Midfielder", age: 31, number: 17 },

  // --- Serie A (80 Players) ---
  { id: 281, name: "Lautaro Martínez", nationality: "Argentina", league: "Serie A", club: "Inter Milan", position: "Attacker", age: 28, number: 10 },
  { id: 282, name: "Nicolò Barella", nationality: "Italy", league: "Serie A", club: "Inter Milan", position: "Midfielder", age: 29, number: 23 },
  { id: 283, name: "Hakan Çalhanoğlu", nationality: "Turkey", league: "Serie A", club: "Inter Milan", position: "Midfielder", age: 32, number: 20 },
  { id: 284, name: "Alessandro Bastoni", nationality: "Italy", league: "Serie A", club: "Inter Milan", position: "Defender", age: 27, number: 95 },
  { id: 285, name: "Federico Dimarco", nationality: "Italy", league: "Serie A", club: "Inter Milan", position: "Defender", age: 28, number: 32 },
  { id: 286, name: "Marcus Thuram", nationality: "France", league: "Serie A", club: "Inter Milan", position: "Attacker", age: 29, number: 9 },
  { id: 287, name: "Yann Sommer", nationality: "Switzerland", league: "Serie A", club: "Inter Milan", position: "Goalkeeper", age: 37, number: 1 },
  { id: 288, name: "Benjamin Pavard", nationality: "France", league: "Serie A", club: "Inter Milan", position: "Defender", age: 30, number: 28 },
  { id: 289, name: "Henrikh Mkhitaryan", nationality: "Armenia", league: "Serie A", club: "Inter Milan", position: "Midfielder", age: 37, number: 22 },
  { id: 290, name: "Denzel Dumfries", nationality: "Netherlands", league: "Serie A", club: "Inter Milan", position: "Defender", age: 30, number: 2 },
  { id: 291, name: "Davide Frattesi", nationality: "Italy", league: "Serie A", club: "Inter Milan", position: "Midfielder", age: 26, number: 16 },
  { id: 292, name: "Piotr Zieliński", nationality: "Poland", league: "Serie A", club: "Inter Milan", position: "Midfielder", age: 32, number: 7 },
  { id: 293, name: "Mehdi Taremi", nationality: "Iran", league: "Serie A", club: "Inter Milan", position: "Attacker", age: 34, number: 99 },
  { id: 294, name: "Yann Bisseck", nationality: "Germany", league: "Serie A", club: "Inter Milan", position: "Defender", age: 25, number: 31 },
  { id: 295, name: "Rafael Leão", nationality: "Portugal", league: "Serie A", club: "AC Milan", position: "Attacker", age: 27, number: 10 },
  { id: 296, name: "Theo Hernández", nationality: "France", league: "Serie A", club: "AC Milan", position: "Defender", age: 28, number: 19 },
  { id: 297, name: "Mike Maignan", nationality: "France", league: "Serie A", club: "AC Milan", position: "Goalkeeper", age: 31, number: 16 },
  { id: 298, name: "Christian Pulisic", nationality: "USA", league: "Serie A", club: "AC Milan", position: "Attacker", age: 27, number: 11 },
  { id: 299, name: "Fikayo Tomori", nationality: "England", league: "Serie A", club: "AC Milan", position: "Defender", age: 28, number: 23 },
  { id: 300, name: "Tijjani Reijnders", nationality: "Netherlands", league: "Serie A", club: "AC Milan", position: "Midfielder", age: 28, number: 14 },
  { id: 301, name: "Ruben Loftus-Cheek", nationality: "England", league: "Serie A", club: "AC Milan", position: "Midfielder", age: 30, number: 8 },
  { id: 302, name: "Álvaro Morata", nationality: "Spain", league: "Serie A", club: "AC Milan", position: "Attacker", age: 33, number: 7 },
  { id: 303, name: "Youssouf Fofana", nationality: "France", league: "Serie A", club: "AC Milan", position: "Midfielder", age: 27, number: 29 },
  { id: 304, name: "Strahinja Pavlović", nationality: "Serbia", league: "Serie A", club: "AC Milan", position: "Defender", age: 25, number: 31 },
  { id: 305, name: "Samuel Chukwueze", nationality: "Nigeria", league: "Serie A", club: "AC Milan", position: "Attacker", age: 27, number: 21 },
  { id: 306, name: "Yunus Musah", nationality: "USA", league: "Serie A", club: "AC Milan", position: "Midfielder", age: 23, number: 80 },
  { id: 307, name: "Dušan Vlahović", nationality: "Serbia", league: "Serie A", club: "Juventus", position: "Attacker", age: 26, number: 9 },
  { id: 308, name: "Bremer", nationality: "Brazil", league: "Serie A", club: "Juventus", position: "Defender", age: 29, number: 3 },
  { id: 309, name: "Teun Koopmeiners", nationality: "Netherlands", league: "Serie A", club: "Juventus", position: "Midfielder", age: 28, number: 8 },
  { id: 310, name: "Kenan Yıldız", nationality: "Turkey", league: "Serie A", club: "Juventus", position: "Attacker", age: 21, number: 10 },
  { id: 311, name: "Manuel Locatelli", nationality: "Italy", league: "Serie A", club: "Juventus", position: "Midfielder", age: 28, number: 5 },
  { id: 312, name: "Andrea Cambiaso", nationality: "Italy", league: "Serie A", club: "Juventus", position: "Defender", age: 26, number: 27 },
  { id: 313, name: "Douglas Luiz", nationality: "Brazil", league: "Serie A", club: "Juventus", position: "Midfielder", age: 28, number: 26 },
  { id: 314, name: "Khéphren Thuram", nationality: "France", league: "Serie A", club: "Juventus", position: "Midfielder", age: 25, number: 19 },
  { id: 315, name: "Francisco Conceição", nationality: "Portugal", league: "Serie A", club: "Juventus", position: "Attacker", age: 23, number: 7 },
  { id: 316, name: "Nicolás González", nationality: "Argentina", league: "Serie A", club: "Juventus", position: "Attacker", age: 28, number: 11 },
  { id: 317, name: "Michele Di Gregorio", nationality: "Italy", league: "Serie A", club: "Juventus", position: "Goalkeeper", age: 29, number: 29 },
  { id: 318, name: "Federico Gatti", nationality: "Italy", league: "Serie A", club: "Juventus", position: "Defender", age: 28, number: 4 },
  { id: 319, name: "Khvicha Kvaratskhelia", nationality: "Georgia", league: "Serie A", club: "Napoli", position: "Attacker", age: 25, number: 77 },
  { id: 320, name: "Romelu Lukaku", nationality: "Belgium", league: "Serie A", club: "Napoli", position: "Attacker", age: 33, number: 11 },
  { id: 321, name: "Scott McTominay", nationality: "Scotland", league: "Serie A", club: "Napoli", position: "Midfielder", age: 29, number: 8 },
  { id: 322, name: "Alessandro Buongiorno", nationality: "Italy", league: "Serie A", club: "Napoli", position: "Defender", age: 27, number: 4 },
  { id: 323, name: "Giovanni Di Lorenzo", nationality: "Italy", league: "Serie A", club: "Napoli", position: "Defender", age: 33, number: 22 },
  { id: 324, name: "Stanislav Lobotka", nationality: "Slovakia", league: "Serie A", club: "Napoli", position: "Midfielder", age: 31, number: 6 },
  { id: 325, name: "André-Frank Zambo Anguissa", nationality: "Cameroon", league: "Serie A", club: "Napoli", position: "Midfielder", age: 30, number: 99 },
  { id: 326, name: "David Neres", nationality: "Brazil", league: "Serie A", club: "Napoli", position: "Attacker", age: 29, number: 7 },
  { id: 327, name: "Billy Gilmour", nationality: "Scotland", league: "Serie A", club: "Napoli", position: "Midfielder", age: 25, number: 65 },
  { id: 328, name: "Alex Meret", nationality: "Italy", league: "Serie A", club: "Napoli", position: "Goalkeeper", age: 29, number: 1 },
  { id: 329, name: "Paulo Dybala", nationality: "Argentina", league: "Serie A", club: "AS Roma", position: "Attacker", age: 32, number: 21 },
  { id: 330, name: "Lorenzo Pellegrini", nationality: "Italy", league: "Serie A", club: "AS Roma", position: "Midfielder", age: 30, number: 7 },
  { id: 331, name: "Artem Dovbyk", nationality: "Ukraine", league: "Serie A", club: "AS Roma", position: "Attacker", age: 29, number: 11 },
  { id: 332, name: "Matías Soulé", nationality: "Argentina", league: "Serie A", club: "AS Roma", position: "Attacker", age: 23, number: 18 },
  { id: 333, name: "Gianluca Mancini", nationality: "Italy", league: "Serie A", club: "AS Roma", position: "Defender", age: 30, number: 23 },
  { id: 334, name: "Bryan Cristante", nationality: "Italy", league: "Serie A", club: "AS Roma", position: "Midfielder", age: 31, number: 4 },
  { id: 335, name: "Evan Ndicka", nationality: "Ivory Coast", league: "Serie A", club: "AS Roma", position: "Defender", age: 26, number: 5 },
  { id: 336, name: "Mile Svilar", nationality: "Serbia", league: "Serie A", club: "AS Roma", position: "Goalkeeper", age: 26, number: 99 },
  { id: 337, name: "Ademola Lookman", nationality: "Nigeria", league: "Serie A", club: "Atalanta", position: "Attacker", age: 28, number: 11 },
  { id: 338, name: "Éderson", nationality: "Brazil", league: "Serie A", club: "Atalanta", position: "Midfielder", age: 27, number: 13 },
  { id: 339, name: "Charles De Ketelaere", nationality: "Belgium", league: "Serie A", club: "Atalanta", position: "Attacker", age: 25, number: 17 },
  { id: 340, name: "Gianluca Scamacca", nationality: "Italy", league: "Serie A", club: "Atalanta", position: "Attacker", age: 27, number: 9 },
  { id: 341, name: "Giorgio Scalvini", nationality: "Italy", league: "Serie A", club: "Atalanta", position: "Defender", age: 22, number: 42 },
  { id: 342, name: "Mateo Retegui", nationality: "Italy", league: "Serie A", club: "Atalanta", position: "Attacker", age: 27, number: 32 },
  { id: 343, name: "Lazar Samardžić", nationality: "Serbia", league: "Serie A", club: "Atalanta", position: "Midfielder", age: 24, number: 24 },
  { id: 344, name: "Marco Carnesecchi", nationality: "Italy", league: "Serie A", club: "Atalanta", position: "Goalkeeper", age: 26, number: 29 },
  { id: 345, name: "Mattia Zaccagni", nationality: "Italy", league: "Serie A", club: "Lazio", position: "Attacker", age: 31, number: 10 },
  { id: 346, name: "Matteo Guendouzi", nationality: "France", league: "Serie A", club: "Lazio", position: "Midfielder", age: 27, number: 8 },
  { id: 347, name: "Alessio Romagnoli", nationality: "Italy", league: "Serie A", club: "Lazio", position: "Defender", age: 31, number: 13 },
  { id: 348, name: "Ivan Provedel", nationality: "Italy", league: "Serie A", club: "Lazio", position: "Goalkeeper", age: 32, number: 94 },
  { id: 349, name: "Boulaye Dia", nationality: "Senegal", league: "Serie A", club: "Lazio", position: "Attacker", age: 29, number: 19 },
  { id: 350, name: "Nuno Tavares", nationality: "Portugal", league: "Serie A", club: "Lazio", position: "Defender", age: 26, number: 30 },
  { id: 351, name: "Moise Kean", nationality: "Italy", league: "Serie A", club: "Fiorentina", position: "Attacker", age: 26, number: 20 },
  { id: 352, name: "David de Gea", nationality: "Spain", league: "Serie A", club: "Fiorentina", position: "Goalkeeper", age: 35, number: 43 },
  { id: 353, name: "Dodô", nationality: "Brazil", league: "Serie A", club: "Fiorentina", position: "Defender", age: 27, number: 2 },
  { id: 354, name: "Albert Guðmundsson", nationality: "Iceland", league: "Serie A", club: "Fiorentina", position: "Attacker", age: 29, number: 10 },
  { id: 355, name: "Andrea Colpani", nationality: "Italy", league: "Serie A", club: "Fiorentina", position: "Midfielder", age: 27, number: 23 },
  { id: 356, name: "Lucas Beltrán", nationality: "Argentina", league: "Serie A", club: "Fiorentina", position: "Attacker", age: 25, number: 9 },
  { id: 357, name: "Patrick Cutrone", nationality: "Italy", league: "Serie A", club: "Como", position: "Attacker", age: 28, number: 10 },
  { id: 358, name: "Gabriel Strefezza", nationality: "Brazil", league: "Serie A", club: "Como", position: "Attacker", age: 29, number: 7 },
  { id: 359, name: "Nico Paz", nationality: "Argentina", league: "Serie A", club: "Como", position: "Midfielder", age: 21, number: 79 },
  { id: 360, name: "Pepe Reina", nationality: "Spain", league: "Serie A", club: "Como", position: "Goalkeeper", age: 43, number: 25 },

  // --- Bundesliga (70 Players) ---
  { id: 361, name: "Harry Kane", nationality: "England", league: "Bundesliga", club: "Bayern Munich", position: "Attacker", age: 33, number: 9 },
  { id: 362, name: "Jamal Musiala", nationality: "Germany", league: "Bundesliga", club: "Bayern Munich", position: "Midfielder", age: 23, number: 42 },
  { id: 363, name: "Leroy Sané", nationality: "Germany", league: "Bundesliga", club: "Bayern Munich", position: "Attacker", age: 30, number: 10 },
  { id: 364, name: "Joshua Kimmich", nationality: "Germany", league: "Bundesliga", club: "Bayern Munich", position: "Midfielder", age: 31, number: 6 },
  { id: 365, name: "Alphonso Davies", nationality: "Canada", league: "Bundesliga", club: "Bayern Munich", position: "Defender", age: 25, number: 19 },
  { id: 366, name: "Manuel Neuer", nationality: "Germany", league: "Bundesliga", club: "Bayern Munich", position: "Goalkeeper", age: 40, number: 1 },
  { id: 367, name: "Dayot Upamecano", nationality: "France", league: "Bundesliga", club: "Bayern Munich", position: "Defender", age: 27, number: 2 },
  { id: 368, name: "Kim Min-jae", nationality: "South Korea", league: "Bundesliga", club: "Bayern Munich", position: "Defender", age: 29, number: 3 },
  { id: 369, name: "Michael Olise", nationality: "France", league: "Bundesliga", club: "Bayern Munich", position: "Attacker", age: 24, number: 17 },
  { id: 370, name: "João Palhinha", nationality: "Portugal", league: "Bundesliga", club: "Bayern Munich", position: "Midfielder", age: 31, number: 16 },
  { id: 371, name: "Serge Gnabry", nationality: "Germany", league: "Bundesliga", club: "Bayern Munich", position: "Attacker", age: 31, number: 7 },
  { id: 372, name: "Thomas Müller", nationality: "Germany", league: "Bundesliga", club: "Bayern Munich", position: "Attacker", age: 36, number: 25 },
  { id: 373, name: "Aleksandar Pavlović", nationality: "Germany", league: "Bundesliga", club: "Bayern Munich", position: "Midfielder", age: 22, number: 45 },
  { id: 374, name: "Mathys Tel", nationality: "France", league: "Bundesliga", club: "Bayern Munich", position: "Attacker", age: 21, number: 39 },
  { id: 375, name: "Hiroki Ito", nationality: "Japan", league: "Bundesliga", club: "Bayern Munich", position: "Defender", age: 27, number: 21 },
  { id: 376, name: "Florian Wirtz", nationality: "Germany", league: "Bundesliga", club: "Bayer Leverkusen", position: "Midfielder", age: 23, number: 10 },
  { id: 377, name: "Álex Grimaldo", nationality: "Spain", league: "Bundesliga", club: "Bayer Leverkusen", position: "Defender", age: 30, number: 20 },
  { id: 378, name: "Jeremie Frimpong", nationality: "Netherlands", league: "Bundesliga", club: "Bayer Leverkusen", position: "Defender", age: 25, number: 30 },
  { id: 379, name: "Granit Xhaka", nationality: "Switzerland", league: "Bundesliga", club: "Bayer Leverkusen", position: "Midfielder", age: 33, number: 34 },
  { id: 380, name: "Victor Boniface", nationality: "Nigeria", league: "Bundesliga", club: "Bayer Leverkusen", position: "Attacker", age: 25, number: 22 },
  { id: 381, name: "Exequiel Palacios", nationality: "Argentina", league: "Bundesliga", club: "Bayer Leverkusen", position: "Midfielder", age: 27, number: 25 },
  { id: 382, name: "Jonathan Tah", nationality: "Germany", league: "Bundesliga", club: "Bayer Leverkusen", position: "Defender", age: 30, number: 4 },
  { id: 383, name: "Edmond Tapsoba", nationality: "Burkina Faso", league: "Bundesliga", club: "Bayer Leverkusen", position: "Defender", age: 27, number: 12 },
  { id: 384, name: "Piero Hincapié", nationality: "Ecuador", league: "Bundesliga", club: "Bayer Leverkusen", position: "Defender", age: 24, number: 3 },
  { id: 385, name: "Lukáš Hrádecký", nationality: "Finland", league: "Bundesliga", club: "Bayer Leverkusen", position: "Goalkeeper", age: 36, number: 1 },
  { id: 386, name: "Martin Terrier", nationality: "France", league: "Bundesliga", club: "Bayer Leverkusen", position: "Attacker", age: 29, number: 11 },
  { id: 387, name: "Aleix García", nationality: "Spain", league: "Bundesliga", club: "Bayer Leverkusen", position: "Midfielder", age: 29, number: 24 },
  { id: 388, name: "Julian Brandt", nationality: "Germany", league: "Bundesliga", club: "Borussia Dortmund", position: "Midfielder", age: 30, number: 10 },
  { id: 389, name: "Gregor Kobel", nationality: "Switzerland", league: "Bundesliga", club: "Borussia Dortmund", position: "Goalkeeper", age: 28, number: 1 },
  { id: 390, name: "Nico Schlotterbeck", nationality: "Germany", league: "Bundesliga", club: "Borussia Dortmund", position: "Defender", age: 26, number: 4 },
  { id: 391, name: "Donyell Malen", nationality: "Netherlands", league: "Bundesliga", club: "Borussia Dortmund", position: "Attacker", age: 27, number: 21 },
  { id: 392, name: "Serhou Guirassy", nationality: "Guinea", league: "Bundesliga", club: "Borussia Dortmund", position: "Attacker", age: 30, number: 9 },
  { id: 393, name: "Marcel Sabitzer", nationality: "Austria", league: "Bundesliga", club: "Borussia Dortmund", position: "Midfielder", age: 32, number: 20 },
  { id: 394, name: "Emre Can", nationality: "Germany", league: "Bundesliga", club: "Borussia Dortmund", position: "Midfielder", age: 32, number: 23 },
  { id: 395, name: "Karim Adeyemi", nationality: "Germany", league: "Bundesliga", club: "Borussia Dortmund", position: "Attacker", age: 24, number: 27 },
  { id: 396, name: "Maximilian Beier", nationality: "Germany", league: "Bundesliga", club: "Borussia Dortmund", position: "Attacker", age: 23, number: 14 },
  { id: 397, name: "Waldemar Anton", nationality: "Germany", league: "Bundesliga", club: "Borussia Dortmund", position: "Defender", age: 30, number: 3 },
  { id: 398, name: "Pascal Groß", nationality: "Germany", league: "Bundesliga", club: "Borussia Dortmund", position: "Midfielder", age: 35, number: 13 },
  { id: 399, name: "Yan Couto", nationality: "Brazil", league: "Bundesliga", club: "Borussia Dortmund", position: "Defender", age: 24, number: 2 },
  { id: 400, name: "Jamie Gittens", nationality: "England", league: "Bundesliga", club: "Borussia Dortmund", position: "Attacker", age: 22, number: 43 },
  { id: 401, name: "Xavi Simons", nationality: "Netherlands", league: "Bundesliga", club: "RB Leipzig", position: "Midfielder", age: 23, number: 10 },
  { id: 402, name: "Loïs Openda", nationality: "Belgium", league: "Bundesliga", club: "RB Leipzig", position: "Attacker", age: 26, number: 11 },
  { id: 403, name: "Benjamin Šeško", nationality: "Slovenia", league: "Bundesliga", club: "RB Leipzig", position: "Attacker", age: 23, number: 30 },
  { id: 404, name: "Willi Orbán", nationality: "Hungary", league: "Bundesliga", club: "RB Leipzig", position: "Defender", age: 33, number: 4 },
  { id: 405, name: "David Raum", nationality: "Germany", league: "Bundesliga", club: "RB Leipzig", position: "Defender", age: 28, number: 22 },
  { id: 406, name: "Castello Lukeba", nationality: "France", league: "Bundesliga", club: "RB Leipzig", position: "Defender", age: 23, number: 23 },
  { id: 407, name: "Amadou Haidara", nationality: "Mali", league: "Bundesliga", club: "RB Leipzig", position: "Midfielder", age: 28, number: 8 },
  { id: 408, name: "Péter Gulácsi", nationality: "Hungary", league: "Bundesliga", club: "RB Leipzig", position: "Goalkeeper", age: 36, number: 1 },
  { id: 409, name: "Antonio Nusa", nationality: "Norway", league: "Bundesliga", club: "RB Leipzig", position: "Attacker", age: 21, number: 7 },
  { id: 410, name: "Arthur Vermeeren", nationality: "Belgium", league: "Bundesliga", club: "RB Leipzig", position: "Midfielder", age: 21, number: 18 },
  { id: 411, name: "Ermedin Demirović", nationality: "Bosnia", league: "Bundesliga", club: "VfB Stuttgart", position: "Attacker", age: 28, number: 9 },
  { id: 412, name: "Deniz Undav", nationality: "Germany", league: "Bundesliga", club: "VfB Stuttgart", position: "Attacker", age: 30, number: 26 },
  { id: 413, name: "Chris Führich", nationality: "Germany", league: "Bundesliga", club: "VfB Stuttgart", position: "Attacker", age: 28, number: 27 },
  { id: 414, name: "Maximilian Mittelstädt", nationality: "Germany", league: "Bundesliga", club: "VfB Stuttgart", position: "Defender", age: 29, number: 7 },
  { id: 415, name: "Alexander Nübel", nationality: "Germany", league: "Bundesliga", club: "VfB Stuttgart", position: "Goalkeeper", age: 29, number: 33 },
  { id: 416, name: "Angelo Stiller", nationality: "Germany", league: "Bundesliga", club: "VfB Stuttgart", position: "Midfielder", age: 25, number: 6 },
  { id: 417, name: "Enzo Millot", nationality: "France", league: "Bundesliga", club: "VfB Stuttgart", position: "Midfielder", age: 24, number: 8 },
  { id: 418, name: "Jeff Chabot", nationality: "Germany", league: "Bundesliga", club: "VfB Stuttgart", position: "Defender", age: 28, number: 24 },
  { id: 419, name: "Omar Marmoush", nationality: "Egypt", league: "Bundesliga", club: "Eintracht Frankfurt", position: "Attacker", age: 27, number: 7 },
  { id: 420, name: "Hugo Larsson", nationality: "Sweden", league: "Bundesliga", club: "Eintracht Frankfurt", position: "Midfielder", age: 22, number: 16 },
  { id: 421, name: "Kevin Trapp", nationality: "Germany", league: "Bundesliga", club: "Eintracht Frankfurt", position: "Goalkeeper", age: 36, number: 1 },
  { id: 422, name: "Mario Götze", nationality: "Germany", league: "Bundesliga", club: "Eintracht Frankfurt", position: "Midfielder", age: 34, number: 27 },
  { id: 423, name: "Hugo Ekitike", nationality: "France", league: "Bundesliga", club: "Eintracht Frankfurt", position: "Attacker", age: 24, number: 11 },
  { id: 424, name: "Robin Koch", nationality: "Germany", league: "Bundesliga", club: "Eintracht Frankfurt", position: "Defender", age: 30, number: 4 },
  { id: 425, name: "Vincenzo Grifo", nationality: "Italy", league: "Bundesliga", club: "SC Freiburg", position: "Attacker", age: 33, number: 32 },
  { id: 426, name: "Ritsu Doan", nationality: "Japan", league: "Bundesliga", club: "SC Freiburg", position: "Attacker", age: 28, number: 42 },
  { id: 427, name: "Matthias Ginter", nationality: "Germany", league: "Bundesliga", club: "SC Freiburg", position: "Defender", age: 32, number: 28 },
  { id: 428, name: "Jonas Wind", nationality: "Denmark", league: "Bundesliga", club: "VfL Wolfsburg", position: "Attacker", age: 27, number: 23 },
  { id: 429, name: "Lovro Majer", nationality: "Croatia", league: "Bundesliga", club: "VfL Wolfsburg", position: "Midfielder", age: 28, number: 19 },
  { id: 430, name: "Mohamed Amoura", nationality: "Algeria", league: "Bundesliga", club: "VfL Wolfsburg", position: "Attacker", age: 26, number: 9 },

  // --- Ligue 1 (70 Players) ---
  { id: 431, name: "Gianluigi Donnarumma", nationality: "Italy", league: "Ligue 1", club: "Paris Saint-Germain", position: "Goalkeeper", age: 27, number: 1 },
  { id: 432, name: "Marquinhos", nationality: "Brazil", league: "Ligue 1", club: "Paris Saint-Germain", position: "Defender", age: 32, number: 5 },
  { id: 433, name: "Achraf Hakimi", nationality: "Morocco", league: "Ligue 1", club: "Paris Saint-Germain", position: "Defender", age: 27, number: 2 },
  { id: 434, name: "Vitinha", nationality: "Portugal", league: "Ligue 1", club: "Paris Saint-Germain", position: "Midfielder", age: 26, number: 17 },
  { id: 435, name: "Warren Zaïre-Emery", nationality: "France", league: "Ligue 1", club: "Paris Saint-Germain", position: "Midfielder", age: 20, number: 33 },
  { id: 436, name: "Ousmane Dembélé", nationality: "France", league: "Ligue 1", club: "Paris Saint-Germain", position: "Attacker", age: 29, number: 10 },
  { id: 437, name: "Bradley Barcola", nationality: "France", league: "Ligue 1", club: "Paris Saint-Germain", position: "Attacker", age: 23, number: 29 },
  { id: 438, name: "Gonçalo Ramos", nationality: "Portugal", league: "Ligue 1", club: "Paris Saint-Germain", position: "Attacker", age: 25, number: 9 },
  { id: 439, name: "Randal Kolo Muani", nationality: "France", league: "Ligue 1", club: "Paris Saint-Germain", position: "Attacker", age: 27, number: 23 },
  { id: 440, name: "Nuno Mendes", nationality: "Portugal", league: "Ligue 1", club: "Paris Saint-Germain", position: "Defender", age: 24, number: 25 },
  { id: 441, name: "Lucas Beraldo", nationality: "Brazil", league: "Ligue 1", club: "Paris Saint-Germain", position: "Defender", age: 22, number: 35 },
  { id: 442, name: "João Neves", nationality: "Portugal", league: "Ligue 1", club: "Paris Saint-Germain", position: "Midfielder", age: 21, number: 87 },
  { id: 443, name: "Willian Pacho", nationality: "Ecuador", league: "Ligue 1", club: "Paris Saint-Germain", position: "Defender", age: 24, number: 51 },
  { id: 444, name: "Désiré Doué", nationality: "France", league: "Ligue 1", club: "Paris Saint-Germain", position: "Attacker", age: 21, number: 14 },
  { id: 445, name: "Fabián Ruiz", nationality: "Spain", league: "Ligue 1", club: "Paris Saint-Germain", position: "Midfielder", age: 30, number: 8 },
  { id: 446, name: "Marco Asensio", nationality: "Spain", league: "Ligue 1", club: "Paris Saint-Germain", position: "Attacker", age: 30, number: 11 },
  { id: 447, name: "Aleksandr Golovin", nationality: "Russia", league: "Ligue 1", club: "AS Monaco", position: "Midfielder", age: 30, number: 10 },
  { id: 448, name: "Takumi Minamino", nationality: "Japan", league: "Ligue 1", club: "AS Monaco", position: "Attacker", age: 31, number: 18 },
  { id: 449, name: "Denis Zakaria", nationality: "Switzerland", league: "Ligue 1", club: "AS Monaco", position: "Midfielder", age: 29, number: 6 },
  { id: 450, name: "Vanderson", nationality: "Brazil", league: "Ligue 1", club: "AS Monaco", position: "Defender", age: 25, number: 2 },
  { id: 451, name: "Folarin Balogun", nationality: "USA", league: "Ligue 1", club: "AS Monaco", position: "Attacker", age: 25, number: 9 },
  { id: 452, name: "Thilo Kehrer", nationality: "Germany", league: "Ligue 1", club: "AS Monaco", position: "Defender", age: 29, number: 5 },
  { id: 453, name: "Wilfried Singo", nationality: "Ivory Coast", league: "Ligue 1", club: "AS Monaco", position: "Defender", age: 25, number: 17 },
  { id: 454, name: "Maghnes Akliouche", nationality: "France", league: "Ligue 1", club: "AS Monaco", position: "Midfielder", age: 24, number: 21 },
  { id: 455, name: "Eliesse Ben Seghir", nationality: "Morocco", league: "Ligue 1", club: "AS Monaco", position: "Attacker", age: 21, number: 7 },
  { id: 456, name: "Radosław Majecki", nationality: "Poland", league: "Ligue 1", club: "AS Monaco", position: "Goalkeeper", age: 26, number: 1 },
  { id: 457, name: "Mason Greenwood", nationality: "England", league: "Ligue 1", club: "Marseille", position: "Attacker", age: 24, number: 10 },
  { id: 458, name: "Pierre-Emile Højbjerg", nationality: "Denmark", league: "Ligue 1", club: "Marseille", position: "Midfielder", age: 31, number: 23 },
  { id: 459, name: "Elye Wahi", nationality: "France", league: "Ligue 1", club: "Marseille", position: "Attacker", age: 23, number: 9 },
  { id: 460, name: "Leonardo Balerdi", nationality: "Argentina", league: "Ligue 1", club: "Marseille", position: "Defender", age: 27, number: 5 },
  { id: 461, name: "Adrien Rabiot", nationality: "France", league: "Ligue 1", club: "Marseille", position: "Midfielder", age: 31, number: 25 },
  { id: 462, name: "Valentin Rongier", nationality: "France", league: "Ligue 1", club: "Marseille", position: "Midfielder", age: 31, number: 21 },
  { id: 463, name: "Amine Harit", nationality: "Morocco", league: "Ligue 1", club: "Marseille", position: "Midfielder", age: 29, number: 11 },
  { id: 464, name: "Gerónimo Rulli", nationality: "Argentina", league: "Ligue 1", club: "Marseille", position: "Goalkeeper", age: 34, number: 1 },
  { id: 465, name: "Jonathan Rowe", nationality: "England", league: "Ligue 1", club: "Marseille", position: "Attacker", age: 23, number: 17 },
  { id: 466, name: "Neal Maupay", nationality: "France", league: "Ligue 1", club: "Marseille", position: "Attacker", age: 29, number: 8 },
  { id: 467, name: "Jonathan David", nationality: "Canada", league: "Ligue 1", club: "Lille OSC", position: "Attacker", age: 26, number: 9 },
  { id: 468, name: "Lucas Chevalier", nationality: "France", league: "Ligue 1", club: "Lille OSC", position: "Goalkeeper", age: 24, number: 30 },
  { id: 469, name: "Edon Zhegrova", nationality: "Kosovo", league: "Ligue 1", club: "Lille OSC", position: "Attacker", age: 27, number: 23 },
  { id: 470, name: "Benjamin André", nationality: "France", league: "Ligue 1", club: "Lille OSC", position: "Midfielder", age: 36, number: 21 },
  { id: 471, name: "Angel Gomes", nationality: "England", league: "Ligue 1", club: "Lille OSC", position: "Midfielder", age: 25, number: 8 },
  { id: 472, name: "Bafodé Diakité", nationality: "France", league: "Ligue 1", club: "Lille OSC", position: "Defender", age: 25, number: 18 },
  { id: 473, name: "Tiago Santos", nationality: "Portugal", league: "Ligue 1", club: "Lille OSC", position: "Defender", age: 24, number: 22 },
  { id: 474, name: "Thomas Meunier", nationality: "Belgium", league: "Ligue 1", club: "Lille OSC", position: "Defender", age: 34, number: 12 },
  { id: 475, name: "Florian Sotoca", nationality: "France", league: "Ligue 1", club: "RC Lens", position: "Attacker", age: 35, number: 7 },
  { id: 476, name: "Brice Samba", nationality: "France", league: "Ligue 1", club: "RC Lens", position: "Goalkeeper", age: 32, number: 30 },
  { id: 477, name: "Kevin Danso", nationality: "Austria", league: "Ligue 1", club: "RC Lens", position: "Defender", age: 27, number: 4 },
  { id: 478, name: "Facundo Medina", nationality: "Argentina", league: "Ligue 1", club: "RC Lens", position: "Defender", age: 27, number: 14 },
  { id: 479, name: "Przemysław Frankowski", nationality: "Poland", league: "Ligue 1", club: "RC Lens", position: "Defender", age: 31, number: 29 },
  { id: 480, name: "Andy Diouf", nationality: "France", league: "Ligue 1", club: "RC Lens", position: "Midfielder", age: 23, number: 18 },
  { id: 481, name: "M'Bala Nzola", nationality: "Angola", league: "Ligue 1", club: "RC Lens", position: "Attacker", age: 29, number: 8 },
  { id: 482, name: "Neil El Aynaoui", nationality: "Morocco", league: "Ligue 1", club: "RC Lens", position: "Midfielder", age: 25, number: 23 },
  { id: 483, name: "Marcin Bułka", nationality: "Poland", league: "Ligue 1", club: "OGC Nice", position: "Goalkeeper", age: 26, number: 1 },
  { id: 484, name: "Dante", nationality: "Brazil", league: "Ligue 1", club: "OGC Nice", position: "Defender", age: 42, number: 4 },
  { id: 485, name: "Terem Moffi", nationality: "Nigeria", league: "Ligue 1", club: "OGC Nice", position: "Attacker", age: 27, number: 9 },
  { id: 486, name: "Jérémie Boga", nationality: "Ivory Coast", league: "Ligue 1", club: "OGC Nice", position: "Attacker", age: 29, number: 7 },
  { id: 487, name: "Youssouf Ndayishimiye", nationality: "Burundi", league: "Ligue 1", club: "OGC Nice", position: "Midfielder", age: 27, number: 55 },
  { id: 488, name: "Melvin Bard", nationality: "France", league: "Ligue 1", club: "OGC Nice", position: "Defender", age: 25, number: 26 },
  { id: 489, name: "Jonathan Clauss", nationality: "France", league: "Ligue 1", club: "OGC Nice", position: "Defender", age: 33, number: 92 },
  { id: 490, name: "Youssoufa Moukoko", nationality: "Germany", league: "Ligue 1", club: "OGC Nice", position: "Attacker", age: 21, number: 15 },
  { id: 491, name: "Ludovic Blas", nationality: "France", league: "Ligue 1", club: "Stade Rennais", position: "Attacker", age: 28, number: 11 },
  { id: 492, name: "Arnaud Kalimuendo", nationality: "France", league: "Ligue 1", club: "Stade Rennais", position: "Attacker", age: 24, number: 9 },
  { id: 493, name: "Steve Mandanda", nationality: "France", league: "Ligue 1", club: "Stade Rennais", position: "Goalkeeper", age: 41, number: 30 },
  { id: 494, name: "Adrien Truffert", nationality: "France", league: "Ligue 1", club: "Stade Rennais", position: "Defender", age: 24, number: 3 },
  { id: 495, name: "Albert Grønbæk", nationality: "Denmark", league: "Ligue 1", club: "Stade Rennais", position: "Midfielder", age: 25, number: 8 },
  { id: 496, name: "Alexandre Lacazette", nationality: "France", league: "Ligue 1", club: "Olympique Lyonnais", position: "Attacker", age: 35, number: 10 },
  { id: 497, name: "Rayan Cherki", nationality: "France", league: "Ligue 1", club: "Olympique Lyonnais", position: "Attacker", age: 22, number: 18 },
  { id: 498, name: "Maxence Caqueret", nationality: "France", league: "Ligue 1", club: "Olympique Lyonnais", position: "Midfielder", age: 26, number: 6 },
  { id: 499, name: "Corentin Tolisso", nationality: "France", league: "Ligue 1", club: "Olympique Lyonnais", position: "Midfielder", age: 32, number: 8 },
  { id: 500, name: "Georges Mikautadze", nationality: "Georgia", league: "Ligue 1", club: "Olympique Lyonnais", position: "Attacker", age: 25, number: 69 }
];
